sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION package doc
  - sbt scalafmtTest
  - sbt ++2.11.11 readme/run
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.4
  - 2.13.0-M2
jdk:
  - oraclejdk8
env:
  - SCALAJS_VERSION=0.6.21
  - SCALAJS_VERSION=1.0.0-M1
